import type { MeetingTemplateInfo } from '@lean/shared';

/** Yerleşik toplantı tipi şablonları (Türkçe gündem başlıklarıyla). */
export const MEETING_TEMPLATES: MeetingTemplateInfo[] = [
  {
    key: 'TIER1_DAILY',
    name: 'Tier 1 Günlük Kademe Toplantısı (SQDCP)',
    description: 'Hat bazında günlük 15 dakikalık ayakta toplantı: Güvenlik, Kalite, Teslimat, Maliyet, İnsan.',
    category: 'TIER',
    tier: 1,
    frequency: 'DAILY',
    durationMin: 15,
    agenda: [
      { title: 'Güvenlik (S)', durationMin: 3, description: 'Kaza, ramak kala, güvensiz durum ve davranışlar' },
      { title: 'Kalite (Q)', durationMin: 3, description: 'Dünün uygunsuzlukları, hurda/yeniden işleme, müşteri şikayetleri' },
      { title: 'Teslimat (D)', durationMin: 3, description: 'Planlanan / gerçekleşen üretim, duruşlar' },
      { title: 'Maliyet (C)', durationMin: 3, description: 'Verimlilik, fire, malzeme ve enerji sapmaları' },
      { title: 'İnsan (P)', durationMin: 3, description: 'Devamsızlık, vardiya planı, eğitim ihtiyaçları, ödül / takdir' },
    ],
  },
  {
    key: 'WEEKLY_DEPARTMENT',
    name: 'Haftalık Bölüm Toplantısı (Tier 2)',
    description: 'Bölüm düzeyinde haftalık performans ve aksiyon takibi toplantısı.',
    category: 'DEPARTMENT',
    tier: 2,
    frequency: 'WEEKLY',
    durationMin: 60,
    agenda: [
      { title: 'Önceki toplantı aksiyonlarının gözden geçirilmesi', durationMin: 10 },
      { title: 'Geçen haftanın KPI performansı ve sapmalar', durationMin: 15 },
      { title: 'İş sağlığı ve güvenliği', durationMin: 5 },
      { title: 'Kalite sorunları ve düzeltici faaliyetler', durationMin: 10 },
      { title: 'Üretim ve teslimat durumu', durationMin: 10 },
      { title: 'İyileştirme (Kaizen) konuları', durationMin: 5 },
      { title: 'Yeni aksiyonlar ve kararlar', durationMin: 5 },
    ],
  },
  {
    key: 'MONTHLY_PERFORMANCE',
    name: 'Aylık Performans Toplantısı (Tier 3)',
    description: 'Fabrika / direktörlük düzeyinde aylık performans değerlendirmesi.',
    category: 'DEPARTMENT',
    tier: 3,
    frequency: 'MONTHLY',
    durationMin: 90,
    agenda: [
      { title: 'Önceki ay aksiyonlarının durumu', durationMin: 10 },
      { title: 'KPI sonuçları ve sapma analizleri', durationMin: 25 },
      { title: 'Hoshin / yıllık hedeflerde ilerleme', durationMin: 10 },
      { title: 'Maliyet ve verimlilik', durationMin: 10 },
      { title: 'Kalite performansı (iç ve dış hatalar)', durationMin: 10 },
      { title: 'İş sağlığı ve güvenliği', durationMin: 5 },
      { title: 'Projeler ve iyileştirme çalışmaları', durationMin: 10 },
      { title: 'Kaynak ihtiyaçları, kararlar ve yeni aksiyonlar', durationMin: 10 },
    ],
  },
  {
    key: 'MANAGEMENT_REVIEW',
    name: 'Yönetimin Gözden Geçirmesi (YGG) — ISO 9001:2015 md. 9.3',
    description: 'ISO 9001:2015 madde 9.3.2 girdilerini kapsayan YGG gündemi ve madde 9.3.3 çıktıları.',
    category: 'MANAGEMENT_REVIEW',
    tier: null,
    frequency: 'QUARTERLY',
    durationMin: 120,
    agenda: [
      { title: 'Önceki yönetimin gözden geçirmesi toplantılarında alınan aksiyonların durumu', description: '9.3.2 a) Girdi' },
      { title: 'Kalite yönetim sistemiyle ilgili dış ve iç hususlardaki değişiklikler', description: '9.3.2 b) Girdi' },
      { title: 'Müşteri memnuniyeti ve ilgili tarafların geri bildirimleri', description: '9.3.2 c) Girdi' },
      { title: 'Kalite hedeflerinin ne ölçüde karşılandığı', description: '9.3.2 c) Girdi' },
      { title: 'Proses performansı ve ürün ve hizmetlerin uygunluğu', description: '9.3.2 c) Girdi' },
      { title: 'Uygunsuzluklar ve düzeltici faaliyetler', description: '9.3.2 c) Girdi' },
      { title: 'İzleme ve ölçme sonuçları', description: '9.3.2 c) Girdi' },
      { title: 'Denetim sonuçları (iç ve dış)', description: '9.3.2 c) Girdi' },
      { title: 'Dış tedarikçilerin performansı', description: '9.3.2 c) Girdi' },
      { title: 'Kaynakların yeterliliği', description: '9.3.2 d) Girdi' },
      { title: 'Risk ve fırsatlara yönelik alınan önlemlerin etkinliği', description: '9.3.2 e) Girdi (6.1)' },
      { title: 'İyileştirme fırsatları', description: '9.3.2 f) Girdi' },
      { title: 'Çıktı: İyileştirme fırsatlarına ilişkin kararlar', description: '9.3.3 Çıktılar — kararlar ve aksiyonlar olarak kaydedilir' },
      { title: 'Çıktı: Kalite yönetim sisteminde değişiklik ihtiyaçları', description: '9.3.3 Çıktılar — kararlar ve aksiyonlar olarak kaydedilir' },
      { title: 'Çıktı: Kaynak ihtiyaçları', description: '9.3.3 Çıktılar — kararlar ve aksiyonlar olarak kaydedilir' },
    ],
  },
];

export const templateByKey = (key: string) => MEETING_TEMPLATES.find((t) => t.key === key);
